# Generated by Django 5.2.9 on 2025-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('car_name', models.CharField(blank=True, max_length=300, null=True)),
                ('engine', models.CharField(blank=True, max_length=200, null=True)),
                ('horsepower', models.FloatField(blank=True, null=True)),
                ('total_speed', models.IntegerField(blank=True, null=True)),
                ('cars_price', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.CharField(blank=True, max_length=50, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
