# Generated by Django 5.2.9 on 2025-12-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='raw',
        ),
    ]
